### ISSUE TITLE
Project-Help-operation

### ISSUE THREAD

**Issue by RebelLP** [gpotter2/BattleOfBlocks#1]
Hello,
Preparing project "Funny-Land". I'd like for us, if you do plugins for free. A case after plugins edited. I would have been rad if you could plug "Battle Of Blocks" do for BungeeCotd. Motd and restart the server then concentration during the game. Thank you in advance for your answer.

Facebook: https://www.facebook.com/funnylandczech
Web: http://funny-land.tk/

**Comment by gpotter2** [comment]
Hey !

 

I’m sorry but i am didn’t realy understood what you mean by:

 

“I would have been rad if you could plug "Battle Of Blocks" do for BungeeCotd”

 

Is the plugin not working with BungeeCord ? Why ?

 

Thanks !

 

De : RebelLP [mailto:notifications@github.com] 
Envoyé : jeudi 3 septembre 2015 16:27
À : gpotter2/BattleOfBlocks
Objet : [BattleOfBlocks] Project-Help-operation (#1)

 

Hello,
Preparing project "Funny-Land". I'd like for us, if you do plugins for free. A case after plugins edited. I would have been rad if you could plug "Battle Of Blocks" do for BungeeCotd. Motd and restart the server then concentration during the game. Thank you in advance for your answer.

Facebook: https://www.facebook.com/funnylandczech
Web: http://funny-land.tk/

**Comment by RebelLP** [comment]
Plugin works with BungeeCord odcenil but I would have if you were to add the plugin could MOTD at what stage the game

**Comment by gpotter2** [comment]
Huh…

 

« to add the plugin could MOTD at what stage the game »

 

G.

 

De : RebelLP [mailto:notifications@github.com] 
Envoyé : jeudi 3 septembre 2015 20:03
À : gpotter2/BattleOfBlocks
Cc : gpotter2
Objet : Re: [BattleOfBlocks] Project-Help-operation (#1)

 

Plugin works with BungeeCord odcenil but I would have if you were to add the plugin could MOTD at what stage the game

**Comment by RebelLP** [comment]
OK, you do not want to do JAVA developer for free?

**Comment by gpotter2** [comment]
Sorry but I am currently overloaded.....

With work, school.......

Sorry...

**Comment by RebelLP** [comment]
Aha ok :( Mohl byste pro Nás udelat aspoň 1 zásuvný modul?
